//
// Created by Sander on 3-4-2017.
//

#ifndef C_AND_D_PROJECT_TEXTURETYPES_H
#define C_AND_D_PROJECT_TEXTURETYPES_H
enum TextureTypes {
    LUMBERJACKTEXTURE,
    MINERTEXTURE,
    TREETEXTURE,
    TREEDEPLETEDTEXTURE,
    IRONMINETEXTURE,
    IRONMINEDEPLETEDTEXTURE,
    WAREHOUSETEXTURE,
    WORLDTEXTURE,
    RESTAURANTTEXTURE,
    CAMPFIRETEXTURE,
    BOWTEXTURE,
    AXETEXTURE
};
#endif //C_AND_D_PROJECT_TEXTURETYPES_H
