//
// Created by Sander on 3-4-2017.
//

#ifndef C_AND_D_PROJECT_TEXTURETYPES_H
#define C_AND_D_PROJECT_TEXTURETYPES_H
enum TextureTypes {
    //Selectable units:
    //Not selected:              selected:
    LUMBERJACKTEXTURE,          SEL_LUMBERJACKTEXTURE,
    MINERTEXTURE,               SEL_MINERTEXTURE,
    BOWTEXTURE,                 SEL_BOWTEXTURE,
    AXETEXTURE,                 SEL_AXETEXTURE,

    TREETEXTURE,
    TREEDEPLETEDTEXTURE,
    IRONMINETEXTURE,
    IRONMINEDEPLETEDTEXTURE,
    WAREHOUSETEXTURE,
    CASTLETEXTURE,
    WORLDTEXTURE,
    RESTAURANTTEXTURE,
    CAMPFIRETEXTURE,
};
#endif //C_AND_D_PROJECT_TEXTURETYPES_H
