# OS Configuration
os:
  - linux

language:
   - cpp

install:
   # gtest install workaround
   - sudo apt-get install libgtest-dev libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-image-2.0-0 cppcheck gtest
#   - sudo apt-get install cppcheck
#   - cd /usr/src/gtest
#   - sudo cmake .
#   - sudo make
#   - sudo mv libgtest* /usr/lib/
#   - cd "${TRAVIS_BUILD_DIR}"
   # -- workaround end

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
    - cppcheck src