//
// Created by Sander on 19-3-2017.
//

#ifndef C_AND_D_PROJECT_JOB_TYPE_H
#define C_AND_D_PROJECT_JOB_TYPE_H

enum JobType {
    IRONMINER, GOLDMINER,WOODCUTTER,HUNTER,ENEMY
};

#endif //C_AND_D_PROJECT_JOB_TYPE_H
