//
// Created by robin on 3/11/17.
//

#ifndef C_AND_D_PROJECT_STRATEGY_GOAL_TYPE_H
#define C_AND_D_PROJECT_STRATEGY_GOAL_TYPE_H
enum StrategyGoalType {
    THINK,FOLLOWPATH,WORK,REST,GOEAT,COMBAT,HUNTTARGET
};
#endif //C_AND_D_PROJECT_STRATEGY_GOAL_TYPE_H
