//
// Created by Sander on 20-3-2017.
//

#ifndef C_AND_D_PROJECT_RESOURCE_TYPE_H
#define C_AND_D_PROJECT_RESOURCE_TYPE_H
enum ResourceType {
    TREE,IRONMINE,WAREHOUSE, RESTAURANT, CAMPFIRE
};
#endif //C_AND_D_PROJECT_RESOURCE_TYPE_H
