//
// Created by robin on 3/11/17.
//

#ifndef C_AND_D_PROJECT_ATOMIC_GOAL_TYPE_H
#define C_AND_D_PROJECT_ATOMIC_GOAL_TYPE_H

enum AtomicGoalType {
    WANDER, OBSTACLE_AVOIDANCE, EXPLORE, PLANPATH, TRAVERSEEDGE, SEEK, GATHER, DROP, SLEEP, EAT
};

#endif //C_AND_D_PROJECT_ATOMIC_GOAL_TYPE_H
