//
// Created by Mark on 10-5-2017.
//

#ifndef CONSTRUCT_AND_DESTROY_MOVING_ENTITY_TYPES_H
#define CONSTRUCT_AND_DESTROY_MOVING_ENTITY_TYPES_H

enum MovingEntityType {
    KNIGHT,
    LUMBERJACK,
    GOLDMINER,
    STONEMINER,
    LIGHT_CAVALIER,
    CAVALIER,
    HEAVY_CAVALIER,
    JUGGERNAUT,
    MERCENARY
};

#endif //CONSTRUCT_AND_DESTROY_MOVING_ENTITY_TYPES_H
